### ISSUE TITLE
Set default install path to /@unixroot/usr/local

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/cmake-os2#1]
According to [this](https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html), the default path for the install target is `/usr/local` on Unix-like machines. The OS/2 build seems to fall into this category as well as this is exactly what I see. And it's completely wrong because it will install stuff into a wrong dir if the build drive does not match UNIXROOT (which usually the case on dev machines) and it will never be found by tools (i.e. cmake itself which looks into `/@unixroot/usr/local/lib/cmake` for modules by default in addition to `/@unixroot/usr/lib/cmake`.

The default install path should be therefore `/@unixroot/usr/local` instead of just `/usr/local`.

**Comment by SilvanScherrer** [comment]
Here it goes wrong. Easy to fix
https://github.com/bitwiseworks/cmake-os2/blob/bba111ed1d945a67b3ef733c7b32ed106b793907/Modules/CMakeGenericSystem.cmake#L167

**Comment by SilvanScherrer** [comment]
fixed with the above commit
