### ISSUE TITLE
Qt5 linguist cmake module problems

### ISSUE THREAD

**Issue by martinrotter** [bitwiseworks/cmake-os2#5]
![image](https://user-images.githubusercontent.com/1255302/151964742-128e7677-82c7-436f-9592-748080fcd645.png)

Btw "linguist" package is installed and "lrelease" tool work when invoked directly.

**Comment by SilvanScherrer** [comment]
this is not a cmake issue. it's a qt5 issue, as qt5 provides the cmake files

**Comment by SilvanScherrer** [comment]
see https://github.com/bitwiseworks/qtbase-os2/issues/116
