### ISSUE TITLE
Version control conflict marker left in file

### ISSUE THREAD

**Issue by dryeo** [bitwiseworks/cmake-os2#6]
https://github.com/bitwiseworks/cmake-os2/blob/457ea5c2c18fcc6e125de765b2190cbf45f0dff0/Utilities/cmlibuv/src/unix/udp.c#L442

This breaks compilation, along with various attempts to use ipv6 throughout libuv.
I did install libav-devel but the cmake build doesn't seem to pick it up.

**Comment by SilvanScherrer** [comment]
This leftover is now removed. But most probably still not buildable. As we dont use internal libuv anymore there is no work planned to have it built.
You need to use --system-libuv among others to have it configured. Best is to look how its done in the specfile.
