### ISSUE TITLE
Cmake 3.20.6-3 fails to install with the enclosed error

### ISSUE THREAD

**Issue by Greggk** [bitwiseworks/cmake-os2#8]
ERROR with transaction check vs depsolve:python(abi) = 2.7 is needed by (installed) urlgrabber-3.10.1-10.oc00.noarchpython(abi) = 2.7 is needed by (installed) yum-utils-1.1.31-3.oc00.noarchpython(abi) = 2.7 is needed by (installed) python2-rpm-4.13.0-20.oc00.i686python(abi) = 2.7 is needed by (installed) yum-metadata-parser-1.1.4-7.oc00.i686python(abi) = 2.7 is needed by (installed) mercurial-2.5.2-1.oc00.pentium4python(abi) = 2.7 is needed by (installed) yum-3.4.3-14.oc00.pentium4/@unixroot/usr/bin/python2 is needed by (installed) hplip-3.19.8-3.oc00.i686python27.dll is needed by (installed) python2-rpm-4.13.0-20.oc00.i686python27.dll is needed by (installed) hplip-libs-3.19.8-3.oc00.i686python27.dll is needed by (installed) yum-metadata-parser-1.1.4-7.oc00.i686python27.dll is needed by (installed) mercurial-2.5.2-1.oc00.pentium4python(abi) = 2.7 is needed by python2-pycurl-7.44.1-3.oc00.pentium4python27.dll is needed by python2-pycurl-7.44.1-3.oc00.pentium4Please report this error at https://github.com/bitwiseworks/rpm-issues

Note python 2.7 is installed

**Comment by SilvanScherrer** [comment]
please send me: yum list python*
and make sure crlf is preserved.

**Comment by Greggk** [comment]
I when to RPM-issues originally but it has a statement that you should use it only for packages that don't have their own site.

yum list python* is below. Thanks
https://roderickklein:sg2sp2@members.os2voice.org/rpm/experimental/RPMS/repodata/repomd.xml: [Errno 14] curl#60 - "SSL certificate problem: certificate has expired"
Trying other mirror.
Installed Packages
python.i686                                   2.7.6-25.oc00          installed  
python-libs.i686                              2.7.6-25.oc00          installed  
python-pycurl.i686                            7.19.5.1-2.oc00        installed  
python2-rpm.i686                              4.13.0-20.oc00         installed  
Available Packages
python.i386                                   2.7.6-12.oc00          netlabs-rel
python.pentium4                               2.7.6-25.oc00          netlabs-rel
python-dateutil.noarch                        2.6.0-1.oc00           netlabs-rel
python-dateutil-doc.noarch                    1:2.8.1-3.oc00         netlabs-rel
python-debug.i386                             2.7.6-12.oc00          netlabs-rel
python-debug.i686                             2.7.6-12.oc00          netlabs-rel
python-debug.pentium4                         2.7.6-12.oc00          netlabs-rel
python-debuginfo.i686                         2.7.6-25.oc00          netlabs-rel
python-debuginfo.pentium4                     2.7.6-25.oc00          netlabs-rel
python-devel.i386                             2.7.6-12.oc00          netlabs-rel
python-devel.i686                             2.7.6-25.oc00          netlabs-rel
python-devel.pentium4                         2.7.6-25.oc00          netlabs-rel
python-libs.i386                              2.7.6-12.oc00          netlabs-rel
python-libs.pentium4                          2.7.6-25.oc00          netlabs-rel
python-libxml2.i686                           2.9.10-1.oc00          netlabs-rel
python-libxml2.pentium4                       2.9.10-1.oc00          netlabs-rel
python-lxml.i386                              3.5.0-1.oc00           netlabs-rel
python-lxml.i686                              3.5.0-1.oc00           netlabs-rel
python-lxml.pentium4                          3.5.0-1.oc00           netlabs-rel
python-lxml-docs.noarch                       3.5.0-1.oc00           netlabs-rel
python-magic.i386                             5.04-7.oc00            netlabs-rel
python-magic.i686                             5.04-7.oc00            netlabs-rel
python-magic.pentium4                         5.04-7.oc00            netlabs-rel
python-magic.noarch                           5.30-2.oc00            netlabs-rel
python-packaging-doc.noarch                   16.8-3.oc00            netlabs-rel
python-pycurl.i386                            7.19.5.1-1.oc00        netlabs-rel
python-pycurl.pentium4                        7.19.5.1-2.oc00        netlabs-rel
python-rpm-macros.noarch                      3.9-3.oc00             netlabs-rel
python-srpm-macros.noarch                     3.9-3.oc00             netlabs-rel
python-test.i386                              2.7.6-12.oc00          netlabs-rel
python-test.i686                              2.7.6-25.oc00          netlabs-rel
python-test.pentium4                          2.7.6-25.oc00          netlabs-rel
python-tools.i386                             2.7.6-12.oc00          netlabs-rel
python-tools.i686                             2.7.6-25.oc00          netlabs-rel
python-tools.pentium4                         2.7.6-25.oc00          netlabs-rel
python-unversioned-command.pentium4           3.9.17-1.oc00          netlabs-rel
python2-appdirs.noarch                        1.4.3-2.oc00           netlabs-rel
python2-dateutil.noarch                       1:2.8.1-3.oc00         netlabs-rel
python2-deltarpm.i686                         3.6-1.oc00             netlabs-rel
python2-deltarpm.pentium4                     3.6-1.oc00             netlabs-rel
python2-libcomps.i686                         0.1.15-1.oc00          netlabs-rel
python2-libcomps.pentium4                     0.1.15-1.oc00          netlabs-rel
python2-libxml2.pentium4                      2.9.10-3.oc00          netlabs-rel
python2-libxslt.pentium4                      1.1.34-2.oc00          netlabs-rel
python2-lxml.i686                             3.6.4-2.oc00           netlabs-rel
python2-lxml.pentium4                         4.4.1-1.oc00           netlabs-rel
python2-net-snmp.i686                         1:5.8-1.oc00           netlabs-rel
python2-net-snmp.pentium4                     1:5.8-1.oc00           netlabs-rel
python2-packaging.noarch                      16.8-3.oc00            netlabs-rel
python2-pycurl.pentium4                       7.44.1-3.oc00          netlabs-rel
python2-pyparsing.noarch                      2.1.10-3.oc00          netlabs-rel
python2-pyqt4-sip.pentium4                    4.19.25-1.oc00         netlabs-rel
python2-pyqt5-sip.pentium4                    4.19.25-1.oc00         netlabs-rel
python2-rpm.pentium4                          4.13.0-20.oc00         netlabs-rel
python2-rpm-macros.noarch                     1-3.oc00               netlabs-rel
python2-setuptools.noarch                     34.4.1-4.oc00          netlabs-rel
python2-setuptools_scm.noarch                 3.3.3-2.oc00           netlabs-rel
python2-sip-devel.pentium4                    4.19.25-1.oc00         netlabs-rel
python2-six.noarch                            1.10.0-2.oc00          netlabs-rel
python2.7.pentium4                            2.7.18-3.oc00          netlabs-rel
python2.7-debuginfo.pentium4                  2.7.18-3.oc00          netlabs-rel
python2.7-unversioned-command.pentium4        2.7.18-3.oc00          netlabs-rel
python3.pentium4                              3.9.17-1.oc00          netlabs-rel
python3-PyQt4.pentium4                        4.12.3-1.oc00          netlabs-rel
python3-PyQt4-devel.pentium4                  4.12.3-1.oc00          netlabs-rel
python3-PyQt4-webkit.pentium4                 4.12.3-1.oc00          netlabs-rel
python3-appdirs.noarch                        1.4.3-2.oc00           netlabs-rel
python3-dateutil.noarch                       1:2.8.1-3.oc00         netlabs-rel
python3-devel.pentium4                        3.9.17-1.oc00          netlabs-rel
python3-idle.pentium4                         3.9.17-1.oc00          netlabs-rel
python3-libs.pentium4                         3.9.17-1.oc00          netlabs-rel
python3-libxml2.pentium4                      2.9.10-3.oc00          netlabs-rel
python3-lxml.pentium4                         4.4.1-1.oc00           netlabs-rel
python3-packaging.noarch                      16.8-3.oc00            netlabs-rel
python3-pycurl.pentium4                       7.44.1-3.oc00          netlabs-rel
python3-pyparsing.noarch                      2.1.10-3.oc00          netlabs-rel
python3-pyqt4-sip.pentium4                    4.19.25-1.oc00         netlabs-rel
python3-pyqt5-sip.pentium4                    4.19.25-1.oc00         netlabs-rel
python3-rpm-macros.noarch                     3.9-3.oc00             netlabs-rel
python3-setuptools.noarch                     34.4.1-4.oc00          netlabs-rel
python3-setuptools_scm.noarch                 3.3.3-2.oc00           netlabs-rel
python3-sip-devel.pentium4                    4.19.25-1.oc00         netlabs-rel
python3-six.noarch                            1.10.0-2.oc00          netlabs-rel
python3-test.pentium4                         3.9.17-1.oc00          netlabs-rel
python3-tkinter.pentium4                      3.9.17-1.oc00          netlabs-rel
python3.9-debuginfo.pentium4                  3.9.17-1.oc00          netlabs-rel

**Comment by SilvanScherrer** [comment]
First do yum install python3 python2.7,then all should be fine

**Comment by Greggk** [comment]
That worked thanks
